str="PRAVEEN"
print(str.isupper())
print(str.islower())
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.isalpha())
print(str.partition('e'))
print(str.split('A'))
print(str.isdigit())
print(str.count('a'))
print(len(str))
print(str[:5])
print(str[-2])
print(str[-1:-3])
print(str.startswith("P"))
string="HeLlo"
string.swapcase()
string="I Like bananas"
string.replace("bananas","apples")
string.index('i')
print("ke" in string)
print(string.isalpha())
